export const DEFAULT_BLAME_ENDPOINT = "/__element-source-blame";
export const DEFAULT_CLICK_CAPTURE_ENABLED = true;
export const BLAME_REQUEST_TIMEOUT_MS = 8000;
export const PANEL_Z_INDEX = 2147483647;

export const GIT_EXEC_TIMEOUT_MS = 10000;
export const MAX_REQUEST_BODY_BYTES = 16384;
export const JSON_RESPONSE_SPACE_COUNT = 2;

export const FALLBACK_LINE_NUMBER = 1;
export const UNIX_TIMESTAMP_TO_MS_MULTIPLIER = 1000;


export const INSPECTOR_RADIUS_PX = 6;
export const INSPECTOR_PANEL_PADDING_PX = 12;
export const INSPECTOR_KEY_COLUMN_WIDTH_PX = 96;
export const INSPECTOR_ROW_GAP_PX = 8;
export const INSPECTOR_ROW_MARGIN_BOTTOM_PX = 6;
export const INSPECTOR_SECTION_GAP_PX = 10;
export const INSPECTOR_SECTION_PADDING_PX = 10;
export const INSPECTOR_MODE_BANNER_TOP_PX = 12;
export const INSPECTOR_MODE_BANNER_PADDING_Y_PX = 6;
export const INSPECTOR_MODE_BANNER_PADDING_X_PX = 12;
export const INSPECTOR_MODE_BANNER_GAP_PX = 8;
export const INSPECTOR_MODE_FRAME_INSET_PX = 8;
export const INSPECTOR_MODE_FRAME_BORDER_WIDTH_PX = 1;
export const INSPECTOR_POPUP_TRANSITION_DURATION_MS = 400;
export const INSPECTOR_POPUP_CLOSED_SCALE_RATIO = 0;
export const INSPECTOR_HOVER_PREFETCH_DELAY_MS = 240;
export const INSPECTOR_ACTION_MESSAGE_TIMEOUT_MS = 1800;

export const INSPECTOR_FONT_SIZE_SM_PX = 12;
export const INSPECTOR_FONT_SIZE_XS_PX = 11;
export const INSPECTOR_FONT_SIZE_TITLE_PX = 16;
export const INSPECTOR_FONT_WEIGHT_MEDIUM = 600;
export const INSPECTOR_FONT_WEIGHT_BOLD = 700;
export const INSPECTOR_LETTER_SPACING_EM = 0.2;
export const INSPECTOR_LINE_HEIGHT = 1.4;
export const INSPECTOR_LINE_HEIGHT_COMPACT = 1;
export const INSPECTOR_FONT_FAMILY = "'Manrope', 'Open Sans', 'Inter', 'Avenir Next', 'Helvetica Neue', sans-serif";

export const INSPECTOR_HOVER_LABEL_OFFSET_Y_PX = 6;
export const INSPECTOR_HOVER_LABEL_PADDING_Y_PX = 6;
export const INSPECTOR_HOVER_LABEL_PADDING_X_PX = 10;
export const INSPECTOR_HOVER_LABEL_MAX_WIDTH_PX = 420;
export const INSPECTOR_HOVER_LABEL_VIEWPORT_MARGIN_PX = 8;
export const INSPECTOR_HOVER_OUTLINE_WIDTH_PX = 2;
export const INSPECTOR_HOVER_OUTLINE_RADIUS_PX = 0;
export const INSPECTOR_HOVER_MIN_SIZE_PX = 1;
export const INSPECTOR_HOVER_SEARCH_MAX_ANCESTORS = 12;
export const INSPECTOR_HOVER_LABEL_RESERVED_HEIGHT_PX = 36;
export const INSPECTOR_HOVER_TRANSITION_DURATION_MS = 210;
export const INSPECTOR_HOVER_LABEL_TRANSITION_DURATION_MS = 210;

export const SOURCE_REFERENCE_MAX_LINE_NUMBER = 1000000;
export const SOURCE_REFERENCE_MIN_LINE_NUMBER = 1;

export const HTTP_STATUS_OK = 200;
export const HTTP_STATUS_BAD_REQUEST = 400;
export const HTTP_STATUS_NOT_FOUND = 404;
export const HTTP_STATUS_METHOD_NOT_ALLOWED = 405;
export const HTTP_STATUS_PAYLOAD_TOO_LARGE = 413;
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
